### PR TITLE
Add basic suppoort for php 8.3

### PR DESCRIPTION
**Pull request by xvilo**
Add basic support for PHP 8.3, when running the test suite locally all tests are passing

### CODE REVIEW

**Comment by xvilo** [comment]
I see there are some unrelated linting steps failing, does the project expect me to fix them or can we leave them as is?

**Comment by gsteel** [comment]
@xvilo 
It would be great if you could get CI green here. There are a bunch of trailing spaces in the README and some extra blank lines - If you could trim those as per the error messages here:
https://github.com/laminas/laminas-mime/actions/runs/6731571212/job/18296531885?pr=35#step:3:218

… it would be very much appreciated, and it would fix CI for both Docs and README linting jobs.

**Comment by xvilo** [comment]
@gsteel It seems the README linting issues are resolved with my latest commit. However, the `Autocloser / autoclose` job is still failing because of a missing token. I expect this to not be an issue, but I have no clear idea on what it does. 

Please do let me know this also needs to be addressed, otherwise I hope this can be merged 🎉

**Comment by xvilo** [comment]
@gsteel It seems the README linting issues are resolved with my latest commit. However, the `Autocloser / autoclose` job is still failing because of a missing token. I expect this to not be an issue, but I have no clear idea on what it does. 

Please do let me know this also needs to be addressed, otherwise I hope this can be merged 🎉

**Review by Ocramius — APPROVED** [review]
Thanks @xvilo!

**Comment by xvilo** [comment]
Thanks, @Ocramius, that was fast ❤️

**Pull request merged**
